language: ruby
rvm:
  - 2.6.3
cache: bundler
branches:
  only:
  - master
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild
deploy:
  provider: pages
  local-dir: ./site
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master