- title: Frontend
  icon: laptop-code
  technologies:
    - title: HTML5
    - title: CSS3
    - title: JavaScript (ES6+)
- title: Backend
  icon: terminal
  technologies:
    - title: Node.js
    - title: Express
    - title: Java
    - title: Golang
    - title: MySQL
    - title: PostgreSQL
    - title: MongoDB
    - title: Neo4j
- title: DevOps    
  icon: cogs
  technologies:
    - title: Git
    - title: Jenkins
    - title: Docker
    - title: Kubernetes
    - title: Ansible
    - title: Docker Swarm